name: Test Lint On PR
on: [pull_request_target]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: npm install
      - run: npm run lint
      # If lint fixes issues, files will be changed. If so, fail the build.
      - run: git diff --exit-code